### ISSUE TITLE
readme中预训练模型的Google网盘无权限

### ISSUE THREAD

**Issue by Michealqiuzack** [XinZhangRadar/Ship-Go#5]
请问您能分享一下训练好的模型吗，给的谷歌网盘无访问权限。感谢！！
![屏幕截图 2024-04-24 202349](https://github.com/XinZhangRadar/Ship-Go/assets/95060687/f3ae79e8-c2e0-44d3-80bc-e694347a76b3)
![屏幕截图 2024-04-24 202809](https://github.com/XinZhangRadar/Ship-Go/assets/95060687/db08f263-6091-403d-bff9-474bf0017b02)

**Comment by XinZhangRadar** [comment]
BaiDu Netdisk：https://pan.baidu.com/s/1CFJ2y31lx4-SY4DBwc5cVw key：e2iy

**Comment by Michealqiuzack** [comment]
感谢

**Comment by Jordan-Liao** [comment]
您好，您的工作真有意义！百度网盘链接已失效，能否再提供一下呢？感谢!
