### ISSUE TITLE
请问运行test的时候应该修改config的哪里呀？

### ISSUE THREAD

**Issue by yakiratian** [XinZhangRadar/Ship-Go#7]
您好，我想用您在别的问题下面提供的训练好的模型权重直接测试数据集，但不知道给的权重5000.state和5000_BCDif.pth该如何使用，希望能得到您的指导，谢谢！

**Comment by Jordan-Liao** [comment]
我也有同样的问题，请问权重5000.state和5000_BCDif.pth该放在哪个位置呢？

**Comment by XinZhangRadar** [comment]
> 我也有同样的问题，请问权重5000.state和5000_BCDif.pth该放在哪个位置呢？

config里的config文件中，resume_state定义了读取模型的路径。如“experiments/train_i2i_sar_221013_001457/checkpoint/5000”，代表读取checkpoint文件夹下，5000_BCDif.pth参数。因此你可以自己定义文件夹，然后在resume_state参数中注明路径以及读取第几轮的模型。

**Comment by Jordan-Liao** [comment]
> > 我也有同样的问题，请问权重5000.state和5000_BCDif.pth该放在哪个位置呢？
> 
> config里的config文件中，resume_state定义了读取模型的路径。如“experiments/train_i2i_sar_221013_001457/checkpoint/5000”，代表读取checkpoint文件夹下，5000_BCDif.pth参数。因此你可以自己定义文件夹，然后在resume_state参数中注明路径以及读取第几轮的模型。
请问，我在这输入的你分享的5000_BCDif和5000.state,生成的结果都是纯噪声背景？有没有什么调整建议？非常感谢作者大大！
![Image](https://github.com/user-attachments/assets/07116f55-99df-4860-b02c-c1b28c6afdaa)

![Image](https://github.com/user-attachments/assets/c6daaeba-caec-4e4f-b62f-e8cff512d255)

**Comment by XinZhangRadar** [comment]
> > > 我也有同样的问题，请问权重5000.state和5000_BCDif.pth该放在哪个位置呢？
> > 
> > 
> > config里的config文件中，resume_state定义了读取模型的路径。如“experiments/train_i2i_sar_221013_001457/checkpoint/5000”，代表读取checkpoint文件夹下，5000_BCDif.pth参数。因此你可以自己定义文件夹，然后在resume_state参数中注明路径以及读取第几轮的模型。
> > 请问，我在这输入的你分享的5000_BCDif和5000.state,生成的结果都是纯噪声背景？有没有什么调整建议？非常感谢作者大大！
> > ![Image](https://github.com/user-attachments/assets/07116f55-99df-4860-b02c-c1b28c6afdaa)
> 
> ![Image](https://github.com/user-attachments/assets/c6daaeba-caec-4e4f-b62f-e8cff512d255)

这个是模型权重没读对。。。resume_state这个路径里，最后要加上权重文件的序号，如：XXX/XXX/XXX/ship-go-weights/5000  。 此时权重文件是保存在ship-go-weights里的。
